name: Criando uma imagem do projeto

on:
    push:
        branches: ["*"]

jobs:
    biuld:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-php@v1
              with:
                  php: 8
                
